### ISSUE TITLE
invalid styles.css

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#1]
your styles.css should sit in the root of your plugin (not within a css folder) - all styles.css files are cached by Moodle in single css file and should also be very specific and prefixed with appropriate classes - for example.
```
.course_grid_img {
```
is not specific enough.

Moodle automatically adds some useful classes to the body tag that relate to the page path - for example all files loaded in the path local/erucart will have path-local-erucart added as a class in the body tag so you should be able to use:

```
.path-local-erucart .course_grid_img {
```
Please see other plugins for examples.

Also - styles.css is NOT something that should be added to your thirdpartylibs.xml file - the only items in that file should be external libraries that you have included in your plugin download.

**Comment by eruditiontec** [comment]
Solved.

**Comment by eruditiontec** [comment]
Thank you so much for your review.
