### ISSUE TITLE
injecting variables into in-line sql is not allowed

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#10]
https://github.com/eruditiontec/moodle_local_erucart/blob/master/settings/coupons.php#L85

https://github.com/eruditiontec/moodle_local_erucart/blob/master/shop/checkout.php#L42

Please use Moodle DB API functions to pass these as parameters to the db functions.
Moodle has a "get_in_or_equal" function to help with the 2nd example I gave above.

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
Please review this again. I can still see sql in your code that has variables injected into the inline sql instead of being passed as parameters.

**Comment by eruditiontec** [comment]
Fixed.
