### ISSUE TITLE
incorrect function names

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#11]
All functions must be namespaced or use the frankenstyle plugin prefix. 

eg function add_coupon() in lib.php should be:
local_erucart_add_coupon()

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
looks like just the class coupon_form  missed which  should also be prefixed with the plugin name (or namespaced.)

**Comment by eruditiontec** [comment]
Fixed.
