### ISSUE TITLE
direct access to $_GET/$_POST not allowed

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#2]
direct access to raw $_GET/$_POST/$_REQUEST is not allowed. Please replace these with appropriate API calls to optional_param or required_param with appropriate cleaning parameters.

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
looks like you have just replaced this with INPUT_POST and you have missed the whole point.

POST/GET vars MUST go through a cleaning process and for Moodle this means you MUST use optional_param or required_param with appropriate cleaning parameters or use moodle forms which also handle the cleaning for you. Especially for a plugin that handles payments.

Please revisit this.

**Comment by eruditiontec** [comment]
I have fixed other $_GET / $_POST except this snippet to avoid keep out casual intruders like paypal(enrolment plugin)
if (empty($_POST) or !empty($_GET)) {
    http_response_code(400);
    throw new moodle_exception('invalidrequest', 'core_error');
}
Hope this makes sense. Thanks you for the guidence.
