### ISSUE TITLE
misleading content in plugin db description

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#3]
in your plugin db description you state " It introduces the "Cart" system in Moodle for the very first time
 - this is not correct.. There are a number of other plugins that implement cart functionality in Moodle. Please remove this statement.

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
thanks - feel free to close this - it looks better than it did before.

**Comment by eruditiontec** [comment]
Thanks.
