### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#4]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. 

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - this issue is not currently a blocker for approval in the plugins db.

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
you have implement the null privacy provider, but this is not correct because your plugin stores user data in the usage/cart and order tables You must implement a number of functions to fix this.

**Comment by eruditiontec** [comment]
As per my knowledge, I will try to implement the support for privacy API.
