### ISSUE TITLE
very old version of jquery lib included in plugin

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#6]
Moodle already includes a core/maintained version of the jquery lib. You should remove your old (2.2.4) version of the jquery.js lib and just re-use the version Moodle provides.

**Comment by eruditiontec** [comment]
Thanks for your feedback! Can you guide us regarding reusability of moodle default jquery library?

**Comment by danmarsden** [comment]
Best to ask that question in the moodle.org community forums - unfortunately the plugin review team doesn't have enough time to provide mentoring support

**Comment by eruditiontec** [comment]
Thanks for your comment, we have resolved this issue. Please check when you have the chance.

**Comment by danmarsden** [comment]
yes - that looks cleaner - feel free to close this.

**Comment by eruditiontec** [comment]
Thank you so much for your review.
