### ISSUE TITLE
consider use of recordsets

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#8]
In some sites this will return a massive dataset.
https://github.com/eruditiontec/moodle_local_erucart/blob/master/settings/coupon_form.php#L78
It would be better to replace this with a recordset.
see here for more info:
https://docs.moodle.org/dev/Data_manipulation_API#Using_Recordsets

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
looks like you're missing the corresponding "close()" function when the recordset has been finished with. You need to add this in just after your loop.

**Comment by eruditiontec** [comment]
Fixed.
