### ISSUE TITLE
anyone logged in can delete a coupon/view all coupons/create coupons.

### ISSUE THREAD

**Issue by danmarsden** [eruditiontec/moodle_local_erucart#9]
The coupondelete.php file appears to allow anyone logged in to delete all coupons. Shouldn't there be a capbilitiy check to see if the user can delete the coupon id being passed?

**Comment by danmarsden** [comment]
this appears to be a bigger issue - none of the coupon handling files appear to make any capability checks. It appears that anyone logged in can create/delete/edit all coupons in the site.

**Comment by eruditiontec** [comment]
Solved.

**Comment by danmarsden** [comment]
good to see the better capability checks - feel free to close this.

**Comment by eruditiontec** [comment]
Thank you so much for your review.
